"""Renamed describe column to description

Revision ID: 73968f3e3463
Revises: cd96eaa3a301
Create Date: 2025-02-08 14:48:49.183707

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '73968f3e3463'
down_revision = 'cd96eaa3a301'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('email')
        batch_op.drop_index('telephone')
        batch_op.drop_index('username')

    op.drop_table('user')
    with op.batch_alter_table('dataset_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cuda', sa.Boolean(), nullable=False))
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('path',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('size',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('model_table', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('image',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=False)
        batch_op.alter_column('input',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_column('output')

    with op.batch_alter_table('user_table', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('telephone',
               existing_type=mysql.VARCHAR(length=15),
               nullable=False)
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_unique_constraint(None, ['telephone'])
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_table', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('telephone',
               existing_type=mysql.VARCHAR(length=15),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('model_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('output', mysql.VARCHAR(length=100), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('input',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('image',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('dataset_table', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('size',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('path',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('cuda')

    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('telephone', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('landline', mysql.VARCHAR(length=8), nullable=False),
    sa.Column('seat', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('role', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('join_time', mysql.DATETIME(), nullable=True),
    sa.Column('management_subject', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('superior', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('group', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('username', ['username'], unique=True)
        batch_op.create_index('telephone', ['telephone'], unique=True)
        batch_op.create_index('email', ['email'], unique=True)

    # ### end Alembic commands ###
