"""empty message

Revision ID: 8effa3654c6b
Revises: 
Create Date: 2025-01-15 12:24:18.649044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8effa3654c6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('telephone', sa.String(length=11), nullable=False),
    sa.Column('landline', sa.String(length=8), nullable=False),
    sa.Column('seat', sa.String(length=20), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.Column('join_time', sa.DateTime(), nullable=True),
    sa.Column('management_subject', sa.String(length=20), nullable=False),
    sa.Column('superior', sa.String(length=20), nullable=False),
    sa.Column('group', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telephone'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
