"""empty message

Revision ID: cd96eaa3a301
Revises: 8effa3654c6b
Create Date: 2025-01-15 12:31:22.578166

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd96eaa3a301'
down_revision = '8effa3654c6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('telephone',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=11),
               type_=sa.String(length=15),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('telephone',
               existing_type=sa.String(length=15),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=11),
               existing_nullable=False)

    # ### end Alembic commands ###
